### ISSUE TITLE
Instructions for linux? 

### ISSUE THREAD

**Issue by ubernaut** [crb02005/gimp-segment-anything#1]
Any chance someone could provide instructions for Ubuntu or linux in genera? 

thanks

**Comment by crb02005** [comment]
I'll add them soon, if you beat me to it feel free to make a pull request.

**Comment by crb02005** [comment]
https://bbs.archlinux.org/viewtopic.php?id=253710   Looks like they pulled python support, probably won't update the instructions until I build a C version. I've got other things I'm building at the moment.

**Comment by crb02005** [comment]
Their docs are currently missing the C example: https://developer.gimp.org/resource/writing-a-plug-in/1/ see https://developer.gimp.org/resource/writing-a-plug-in/1/hello.c

**Comment by ubernaut** [comment]
Much appreciated anyway.
